# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
pool:
  vmImage: 'ubuntu-16.04'

container: mcr.microsoft.com/dotnet/core/sdk:2.2

resources:
  containers:
  - container: redis
    image: redis

services:
  redis: redis

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration release'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests.csproj'
    arguments: '--configuration release'
  env:
    CONNECTIONSTRINGS_REDIS: redis:6379

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    projects: 'MyProject/MyProject.csproj'
    publishWebProjects: false
    zipAfterPublish: false
    arguments: '--configuration release'

- task: PublishPipelineArtifact@0
  displayName: Store artefact
  inputs:
    artifactName: 'MyProject'
    targetPath: 'MyProject/bin/release/netcoreapp2.2/publish/'   

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'azure-devops'
    command: 'buildAndPush'
    Dockerfile: 'https://artprodsin1.artifacts.visualstudio.com/A1518c0af-fead-4cb5-a115-e66404b4f6ac/14345487-234e-4e44-8a32-93c193b7f20e/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3ZpbWFsZXNobjQ4L3Byb2plY3RJZC8xNDM0NTQ4Ny0yMzRlLTRlNDQtOGEzMi05M2MxOTNiN2YyMGUvYnVpbGRJZC8xMTMvYXJ0aWZhY3ROYW1lL015UHJvamVjdA2/content?format=file&subPath=%2FDockerfile'