resources:
  containers:
  - container: linux # reusable alias
    image: ubuntu:16.04
  - container: windows # reusable alias
    image: windows:latest
stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: echo Testing on Linux!