
stages:
- stage: Build
  jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: echo build on Linux!
  - job: windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: echo build on windows!
  