stages:
- stage: Build and publish
  jobs:
  - job: 
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration release'
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        projects: 'MyProject/MyProject.csproj'
        publishWebProjects: false
        zipAfterPublish: false
        arguments: '--configuration release'
# jobs:
# - job: 
#   pool:
#     vmImage: 'ubuntu-16.04'
  
#   - stage: Build
#     steps:
#     - task: DotNetCoreCLI@2
#       inputs:
#         command: 'build'
#         projects: '**/*.csproj'
#         arguments: '--configuration release'

# - stage: Publish
#   jobs:
#   - job: Publish-on-linux
    